### ISSUE TITLE
I don't understand how to set it up

### ISSUE THREAD

**Issue by ppppow** [ToneDen/toneden-sdk#42]
Hey I'm pretty new to adding scripts to websites and I just can't seem to figure out how to get this to work. I even tried just running the "test" index.html and the ToneDen player won't even load on there for me. This is all I see when I run the test index.html:

![screen shot 2015-04-30 at 12 14 50 pm](https://cloud.githubusercontent.com/assets/12188378/7417329/6624e75c-ef33-11e4-812e-f936591e70ee.png)

I'm trying to build a website for my friends who have a soundcloud and would love to be able to implement this ToneDen player on the site, but I just can't figure out how to do that! Any help is greatly appreciated, sorry for being so nooby lol.

**Comment by elsbree** [comment]
The reason the test/index.html isn't loading correctly is probably because you need to set up a web server on your machine. test/index.html tries to load the player from the site 'widget.dev', which doesn't point to anything unless you set up Apache as described in the readme [here](https://github.com/ToneDen/toneden-sdk#setup).

The instructions at that link work apply to Macs, but if you're on Windows or Linux I believe the only difference will be the locations of the configuration files. If you're not familiar with Apache, there's a pretty good guide [here](http://www.webmonkey.com/2010/02/apache_for_beginners/).

If you're having trouble implementing the player in a live site, you can post the URL here and I can take a look to see what might be wrong.

**Comment by ppppow** [comment]
Awesome thank you for such a quick reply! That totally makes sense why its not working now. I'll check out Apache and try and figure out my problems and I'll let you know if I can get it working!

Thanks again.
