### ISSUE TITLE
Visualizer Not functioning

### ISSUE THREAD

**Issue by eythandamico** [ToneDen/toneden-sdk#45]
![screen shot 2015-05-17 at 10 12 29 am](https://cloud.githubusercontent.com/assets/12148204/7670706/5027a94c-fc7d-11e4-8dc6-b369df5cc3b4.png)

**Comment by elsbree** [comment]
A recent version of Chrome broke the visualizer in the player, so unfortunately we had to remove it. There is a big rewrite of the player coming up in our development plan, but we're a small team so it'll take a few months before we can revisit this.

**Comment by elsbree** [comment]
As an update to this: we just released v2, but we haven't looked into reinstating the visualizer just yet. It all depends on how stable the web audio API has become since we last developed the visualizer.

**Comment by HandHugs** [comment]
would love to have the visualizer back. Are you still working on this script?

**Comment by gabbhack** [comment]
i wait)

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
