### ISSUE TITLE
Track lengths in playlist?

### ISSUE THREAD

**Issue by muranyia** [ToneDen/toneden-sdk#54]
Hello,

can I get each track's length included in the playlist?

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
