### ISSUE TITLE
404 File Not Found.

### ISSUE THREAD

**Issue by travisloneker** [ToneDen/toneden-sdk#56]
Hello, I am able to get the player to work but run into a weird issue when I click on certain areas of the player it links to your main website. http://www.worcommunity.com is where the player is located. I am using someone else's information because I am simply testing to see if this is a solution. Try clicking on the next track button or actually clicking on a track, that's when the linking to ToneDen happens.

Here is a list of errors I am receiving:

Download the React DevTools for a better development experience: https://fb.me/react-devtools
sd.toneden.io/production/v2/toneden.js:4 Warning: Unknown DOM property data-className. Did you mean data-classname?
http://sd.toneden.io/resources/fonts/td-player.woff%27)%20format(%27woff Failed to load resource: the server responded with a status of 403 (Forbidden)
sd.toneden.io/production/v2/toneden.js:4 Warning: Scrubber is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
