### ISSUE TITLE
onTrackReady event disappeared?

### ISSUE THREAD

**Issue by PepeLopez** [ToneDen/toneden-sdk#65]
Hi guys,

I've implemented the first toneden player about many months ago and now got a hint, that Chrome isn't playing music anymore.
So I've upgraded _(\* see below)_ to the latest version of toneden player and recognized, that this code isn't working anymore:

```
player = ToneDen.player.create({
            dom: "#playerdivX",
            skin: "dark",
            tracksPerArtist: 50,
            mini: true,
            onTrackReady: function(){
                console.log("track ready");
                $( "#player" ).animate({ "bottom": "0" }, 1000 );               
            },
            urls: [
                "my.urls..."
            ]
        });
```

That means, "**onTrackReady**" event isn't triggered actually - there is no log to console and no animation anymore. That was possible with the "old" version.

Will this be fixed, or is the event renamed? Unfortunately the docs about that is still missing :(

**(*):** 
I'm not using the "online" toneden player, I downloaded the sources (loader and toneden.js) and using it on my own webspace. For two reasons:
1st: Faster loading - no 2nd dns query
2nd: I can modify the files, because in the latest toneden.js version is a bug

"td-player;src:url(\'//sd.toneden.io/resources/fonts/td-player.woff%27)%20format(%27woff\') "

Dunno why you're using that wrong URI - sd.toneden.io/resources/fonts/td-player.woff%27)%20format(%27woff\')  always throws errors in all of my browsers... changed it to 
"td-player;src:url(\'//sd.toneden.io/resources/fonts/td-player.woff\') "
works like a charm...

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
