### ISSUE TITLE
Single Param Not Being Set To True Automatically For Single Tracks

### ISSUE THREAD

**Issue by jackrugile** [ToneDen/toneden-sdk#68]
According the [main page](https://www.toneden.io/player), it says:

> The player will automatically default to the single-track player below if only one track url is provided.

However, when testing this, I found that I had to explicitly set the `single` property to `true` to get the smaller layout to trigger. [View a demo of this behavior.](http://codepen.io/jackrugile/pen/e9ae378f5f46b3b38040107d2c78cd1e?editors=0010)

Then, after viewing the source for the demo page, I found that `single` is being set to `true` explicitly in the demo page anyway.

Is there anyway to get this to auto-detect whether single should be set to true or not?

Screenshot below of a single track showing up in playlist format:

![screen shot 2016-03-03 at 5 53 29 pm](https://cloud.githubusercontent.com/assets/726153/13514753/ed08ad9e-e168-11e5-80de-e69fb67a7b5f.png)

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
