### ISSUE TITLE
ToneDen.player.global.nowPlaying() only returns false

### ISSUE THREAD

**Issue by danielfilho** [ToneDen/toneden-sdk#69]
no matter if it is playing or not, it only returns false.

More info on this video (without audio, but it was playing):
https://cloudup.com/cmywsF5qqHK

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
