### ISSUE TITLE
Problem with multiple instances

### ISSUE THREAD

**Issue by andygco** [ToneDen/toneden-sdk#80]
When there are multiple instances on a page which are connected to different sets (playlists) on soundcloud, after the first track is complete in the active player, a different player starts playing instead of the second track in the active player.

An example of this behavior is available on [https://andyg.co/hen](https://andyg.co/hen)

Steps to reproduce:
1. Click 'play' on the first toneden player
2. Scroll to the end of the song (or let the first song play to the end)
3. The song completes -- I would then expect the second song in the set associated with the first player to play... this isn't what happens
3. Instead of playing the second song in the set associated with the first player, it begins playing a track in a different player at the bottom of the page

Thanks for your wonderful player!

-- Andy

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
