### ISSUE TITLE
Player stuck on loading in iOS

### ISSUE THREAD

**Issue by JackBrit** [ToneDen/toneden-sdk#81]
Is there a fix for the player stuck loading on any iOS device?

**Comment by dorjegit** [comment]
Same problem here, player is stuck loading only on Safari browser since IOs10.0

**Comment by HandHugs** [comment]
Was having the same issue. Now the player doesn't work at all. Help??

**Comment by elsbree** [comment]
I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
