### ISSUE TITLE
Player no longer working at all

### ISSUE THREAD

**Issue by HandHugs** [ToneDen/toneden-sdk#82]
Can't seem to get the player to work at all anymore. Your demo site is broken too: 
https://www.toneden.io/player

I get these errors: Failed to load resource: the server responded with a status of 401 (Unauthorized)

Tried using my own Consumer Key like in the docs, but when I add it like you have outlined in the docs on here, i get an error, configure is not a function. :(

**Comment by dorjegit** [comment]
error 401 here too.
any solution that may fix the IOS bug by the way?
thanks

**Comment by HandHugs** [comment]
Can't really fix the iOS thing when the whole thing doesn't work 

Jessie Matanky
303-396-5452
mail@handhugs.com

**Comment by elsbree** [comment]
I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 
Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud. It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
